# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8252d9241320156571669f97526d3536feaacdff826e485359e611e51e062eac91e620c726f431569fb69df205643c407e3949b9a11af8bf2b91fdfd7cfce70

test:
  secret_key_base: a34700e8ec0985d6c951370b5ca994a44f93a754fe69ef13ae5ebdb5897a7aa6107a2f1b478d45a40938e9382829a0b4ee295d3ddeb6272a02c6d7df3701cd24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
